### ISSUE TITLE
Questions about random exploration in the early stages of training

### ISSUE THREAD

**Issue by hdadong** [CLeARoboticsLab/ssrl#1]
Hello, this is a very interesting and promising piece of work. What I'm particularly curious about is that in the video shown on your website, the policy at minute 0 already seems to exhibit reasonable actions, without any strange behaviors typically caused by random exploration. I was wondering if the policy was pretrained in simulation, or if the training truly started from scratch? If so, How do you ensure that the robot doesn't perform unsafe actions, such as exceeding joint limits, at the beginning of the training process?  @jake-levy

**Comment by hdadong** [comment]
Before doing real world training, have you pre-trained the world model in the simulator?
In addition to using three minutes of real-world data, have you also used simulated data to speed up training in real-world? @jake-levy

**Comment by jake-levy** [comment]
Hello - thank you for reaching out. Here are answers to your questions:

>  I was wondering if the policy was pretrained in simulation, or if the training truly started from scratch?

The policy is not pretrained at all. The first rollout on hardware is with a randomly initialized policy.

> What I'm particularly curious about is that in the video shown on your website, the policy at minute 0 already seems to exhibit reasonable actions, without any strange behaviors typically caused by random exploration.

The policy outputs foot position offsets to a nominal [gait generator](https://github.com/CLeARoboticsLab/ssrl/blob/main/ssrl/brax/robots/go1/gait.py). This gait generator creates only vertical stepping motion for the feet. At the start of training, the random initialization of the policy produces relatively small actions (due to the initializer we use) and the resulting gait that you see is coming from mostly the gait generator. Also, as mentioned in the [paper](https://openreview.net/pdf?id=evCXwlCMIi), during the real-world rollouts, we do not add exploration noise on top of the policy - we only add exploration noise during hallucination. 

> How do you ensure that the robot doesn't perform unsafe actions, such as exceeding joint limits, at the beginning of the training process?

After desired joint angles are computed by the inverse kinematics solver, we [clip](https://github.com/CLeARoboticsLab/ssrl/blob/d1135d233765da599712adb6fee00792d17e9f05/ssrl/brax/envs/go1_go_fast.py#L1081) the joint angles to ensure they stay within joint limits plus some safety margin.

> Before doing real world training, have you pre-trained the world model in the simulator?

No, the model is initialized from scratch at the beginning of training as well.

 > In addition to using three minutes of real-world data, have you also used simulated data to speed up training in real-world?
 
The model is trained only on real-world data. The policy is trained on a mixture of real-world data and hallucinated data from the model.

**Comment by hdadong** [comment]
Thanks for the clarification, I think SSRL is indeed a great approach.
